# Generated by Django 4.0.5 on 2022-09-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_video_upload_delete_signupuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_upload',
            old_name='Description',
            new_name='Video_Description',
        ),
        migrations.RenameField(
            model_name='video_upload',
            old_name='title',
            new_name='Video_Title',
        ),
    ]
