# Generated by Django 4.0.5 on 2022-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_alter_video_upload_video_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video_upload',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='video_upload',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video_upload',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
