# Generated by Django 4.0.5 on 2022-09-26 10:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_alter_video_upload_options_video_upload_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_upload',
            name='Selec_Track',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Digital Marketers'), (2, 'Full Stack Web Developers'), (3, 'Embedded Systems Engineers'), (4, 'Product/Graphics Designers'), (5, 'Data Scientists')], max_length=9, null=True),
        ),
    ]
