# Generated by Django 4.0.5 on 2022-09-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_video_upload_selec_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_upload',
            old_name='Selec_Track',
            new_name='Select_Track',
        ),
    ]
