# Generated by Django 4.0.5 on 2022-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0009_alter_video_upload_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_upload',
            name='Video_Description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
