# Generated by Django 4.0.5 on 2022-10-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0011_quizes_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizes',
            name='responders',
        ),
    ]
