# Generated by Django 4.0.5 on 2022-10-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0012_remove_quizes_responders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
