# Generated by Django 4.0.5 on 2022-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0014_alter_response_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='prize',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='body',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
