# Generated by Django 4.0.5 on 2022-10-02 20:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0016_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='track',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Digital Marketers'), (2, 'Full Stack Web Developers'), (3, 'Embedded Systems Engineers'), (4, 'Product/Graphics Designers'), (5, 'Data Scientists')], max_length=9, null=True),
        ),
    ]
