# Generated by Django 4.0.5 on 2022-10-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0017_alter_assignment_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='detailed_description',
            field=models.TextField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='short_description',
            field=models.TextField(max_length=300),
        ),
    ]
