# Generated by Django 4.0.5 on 2022-10-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0018_alter_assignment_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='resources',
            field=models.TextField(max_length=1000),
        ),
    ]
