# Generated by Django 4.0.5 on 2022-10-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0019_alter_assignment_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='data_of_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=30000, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='mode_of_submission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='resources',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
