# Generated by Django 4.0.5 on 2022-10-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0021_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='task_point',
            field=models.IntegerField(),
        ),
    ]
