# Generated by Django 4.0.5 on 2022-10-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0022_assignment_submission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment_submission',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
