# Generated by Django 4.0.5 on 2022-10-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0023_alter_assignment_submission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submission',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
