# Generated by Django 4.0.5 on 2022-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0025_remove_assignment_submission_grade_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='track',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
