# Generated by Django 4.0.5 on 2022-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0027_video_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_upload',
            name='Select_Track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
