# Generated by Django 4.0.5 on 2022-10-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0028_alter_video_upload_select_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_upload',
            old_name='Video_Title',
            new_name='Select_Title',
        ),
    ]
