# Generated by Django 4.0.5 on 2022-11-20 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lmsapp', '0029_rename_video_title_video_upload_select_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizes',
            new_name='Rooms',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='quiz',
            new_name='room',
        ),
    ]
