# Generated by Django 4.0.5 on 2022-11-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0030_rename_quizes_rooms_rename_quiz_response_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='prize',
        ),
    ]
