# Generated by Django 4.0.5 on 2022-11-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0031_remove_rooms_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='Asker',
            new_name='user',
        ),
    ]
