# Generated by Django 4.0.5 on 2022-11-24 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lmsapp', '0032_rename_asker_rooms_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('submission', models.CharField(blank=True, max_length=200, null=True)),
                ('time_of_submission', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AlterField(
            model_name='rooms',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
