# Generated by Django 4.0.5 on 2022-11-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0033_gradestudent_alter_rooms_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradestudent',
            name='assignment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
