# Generated by Django 4.0.5 on 2022-09-22 03:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stageonesignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('track', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Full Stack Web Development'), (2, 'Digital Marketing'), (3, 'Product/Graphce Design'), (4, 'Data Science'), (5, 'Embedded Sytems Engineering')], max_length=9)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('dateofbirth', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=200)),
                ('repassword', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
