# Generated by Django 4.0.5 on 2022-09-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageonesignup',
            name='track',
            field=models.CharField(max_length=200),
        ),
    ]
