# Generated by Django 4.0.5 on 2022-09-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0004_remove_stagetwosignup_user_full_stagetwosignup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetwosignup',
            name='stageone',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='useronboard.stageonesignup'),
            preserve_default=False,
        ),
    ]
