# Generated by Django 4.0.5 on 2022-09-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0005_stagetwosignup_stageone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagetwosignup',
            name='user',
        ),
    ]
