# Generated by Django 4.0.5 on 2022-09-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0006_remove_stagetwosignup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagetwosignup',
            name='id',
        ),
        migrations.AlterField(
            model_name='stageonesignup',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stagetwosignup',
            name='stageone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='useronboard.stageonesignup'),
        ),
    ]
