# Generated by Django 4.0.5 on 2022-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0007_remove_stagetwosignup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagetwosignup',
            name='stageone',
        ),
        migrations.AddField(
            model_name='stagetwosignup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
