# Generated by Django 4.0.5 on 2022-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0008_remove_stagetwosignup_stageone_stagetwosignup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('track', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('dateofbirth', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=200)),
                ('repassword', models.CharField(max_length=200)),
                ('github', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedIn', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('portfoliowebsite', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('profilepicture', models.ImageField(upload_to='profilemages')),
            ],
        ),
        migrations.DeleteModel(
            name='stageonesignup',
        ),
        migrations.DeleteModel(
            name='stagetwosignup',
        ),
    ]
