# Generated by Django 4.0.5 on 2022-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0010_user_reg_user_alter_user_reg_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='profilepicture',
            field=models.ImageField(null=True, upload_to='profilemages'),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
