# Generated by Django 4.0.5 on 2022-09-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0011_alter_user_reg_profilepicture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
