# Generated by Django 4.0.5 on 2022-09-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0012_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='email',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
