# Generated by Django 4.0.5 on 2022-09-26 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useronboard', '0014_alter_user_reg_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
