# Generated by Django 4.0.5 on 2022-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0015_alter_user_reg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='profilepicture',
            field=models.ImageField(default='images/userprofilepic.png', null=True, upload_to='profileimages'),
        ),
    ]
